[metadata]
name=stars-mx-cdst-snp-query-box
version=2.12.8
author=NathanLim
author_email=LimS@aetna.com
description=A python library with snp related queries and functions
url=https://github.com/cvs-legacy-source-code/cdst-snp-query-box
project_urls=
    BugTracker=https://github.com/cvs-legacy-source-code/cdst-snp-query-box/issues

[options]
packages = find:
package_dir=
    =src
include_package_data = true
python_requires= >=3.7
install_requires =
    pandas
    google-cloud-core
    google-cloud-pubsub>=2.18
    googleapis-common-protos
    google-cloud-bigquery>=3.11
    google-cloud-bigquery-storage
    numpy>=1.19.1
    joblib

[options.packages.find]
where = src

[options.package_data]
cdst_snp_query_box = 
    data/*
